part of '../app_theme.dart';

final _lightColorPalette = ThemeColorExtension(
  primary: const Color(0xFFD32F2F),
  onPrimary: const Color(0xFFFFFFFF),
  primaryContainer: const Color(0xFFFF6659),
  onPrimaryContainer: const Color(0xFF410003),
  secondary: const Color(0xFFE57373),
  onSecondary: const Color(0xFF5A1B1B),
  secondaryContainer: const Color(0xFFFFDAD4),
  onSecondaryContainer: const Color(0xFF410003),
  tertiary: const Color(0xFFB71C1C),
  onTertiary: const Color(0xFFFFFFFF),
  tertiaryContainer: const Color(0xFFFFCDD2),
  onTertiaryContainer: const Color(0xFF410003),
  error: const Color(0xFFBA1A1A),
  onError: const Color(0xFFFFFFFF),
  errorContainer: const Color(0xFFFFDAD6),
  onErrorContainer: const Color(0xFF410002),
  surface: const Color(0xFFFFF1F0),
  onSurface: const Color(0xFF5A1B1B),
  surfaceContainerHighest: const Color(0xFFFFE4E4),
  onSurfaceVariant: const Color(0xFF9D8A87),
  outline: const Color(0xFF8B6161),
  outlineVariant: const Color(0xFFD8C2C0),
  inversePrimary: const Color(0xFF930006),
  inverseSurface: const Color(0xFF410003),
  onInverseSurface: const Color(0xFFFFB4A9),
  scrim: const Color(0xFF000000),
  shadow: const Color(0xFF000000),
  surfaceTint: const Color(0xFFD32F2F),
  baalsaal: Colors.green,
);
