name: core
description: "Contains shared resources and utilities of 'Flutter Clean MVVM'"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: 3.6.1
  flutter: 3.27.2

dependencies:
  di:
    path: ../di
  cached_network_image: 3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  flutter_html: 3.0.0-beta.2
  flutter_svg: 2.0.17
  intl: 0.19.0
  logger: 2.5.0
  shimmer: 3.0.0

dev_dependencies:
  build_runner: 2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  generate: true
  module:
    androidX: true
    androidPackage: com.example.hasibul.core
    iosBundleIdentifier: com.example.hasibul.core
