name: domain
description: "This is 'Flutter Clean MVVM' template domain layer."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: 3.6.1
  flutter: 3.27.2

dependencies:
  core:
    path: ../core
  di:
    path: ../di
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: 2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  injectable_generator: 2.7.0

flutter:
  uses-material-design: true
  generate: true
  module:
    androidX: true
    androidPackage: com.example.hasibul.domain
    iosBundleIdentifier: com.example.hasibul.domain
