platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug-flavor_prod' => :debug,
  'Profile-flavor_prod' => :release,
  'Release-flavor_prod' => :release,
  'Debug-flavor_dev' => :debug,
  'Profile-flavor_dev' => :release,
  'Release-flavor_dev' => :release,
  'Debug-flavor_test' => :debug,
  'Profile-flavor_test' => :release,
  'Release-flavor_test' => :release,
  'Debug-flavor_staging' => :debug,
  'Profile-flavor_staging' => :release,
  'Release-flavor_staging' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# Define targets for each flavor
['flavor_prod', 'flavor_dev', 'flavor_test', 'flavor_staging'].each do |flavor|
  target flavor do
    use_frameworks!
    use_modular_headers!

    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end