name: di
description: "Dependency injection module of 'Flutter Clean MVVM'"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: 3.6.1
  flutter: 3.27.2

dependencies:
  core:
    path: ../core
  data:
    path: ../data
  domain:
    path: ../domain
  waadaa:
    path: ../
  flutter:
    sdk: flutter
  get_it: 8.0.3
  injectable: 2.5.0

dev_dependencies:
  build_runner: 2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  injectable_generator: 2.7.0

flutter:
  uses-material-design: true
  generate: true
  module:
    androidX: true
    androidPackage: com.example.hasibul.di
    iosBundleIdentifier: com.example.hasibul.di
